apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: im208fl0b-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/im208fl0b-java-quarkus-gitops